"""initial schema

Revision ID: 52409b52db03
Revises: 
Create Date: 2026-06-13 10:12:21.573204
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '52409b52db03'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates')),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    op.create_table('scoring_rules',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_rules')),
    sa.UniqueConstraint('name', 'version', name='uq_scoring_name_version')
    )
    op.create_index(op.f('ix_scoring_rules_name'), 'scoring_rules', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('job_source_configs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('auth_status', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_source_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_source_configs'))
    )
    op.create_index(op.f('ix_job_source_configs_user_id'), 'job_source_configs', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('model_call_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_model_call_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_call_logs'))
    )
    op.create_index(op.f('ix_model_call_logs_task_type'), 'model_call_logs', ['task_type'], unique=False)
    op.create_index(op.f('ix_model_call_logs_user_id'), 'model_call_logs', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('education_level', sa.String(length=32), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('target_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_cities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('industries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('career_interests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('job_analyses',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('responsibilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hard_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('soft_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('bonus_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seniority_level', sa.String(length=32), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_analyses_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_analyses'))
    )
    op.create_index(op.f('ix_job_analyses_job_id'), 'job_analyses', ['job_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_report_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skill_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_versions_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions')),
    sa.UniqueConstraint('resume_id', 'version_no', name='uq_resume_version_no')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('job_discovery_tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_job_discovery_tasks_profile_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_job_discovery_tasks_resume_version_id_resume_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_discovery_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_discovery_tasks'))
    )
    op.create_index(op.f('ix_job_discovery_tasks_status'), 'job_discovery_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_job_discovery_tasks_user_id'), 'job_discovery_tasks', ['user_id'], unique=False)
    op.create_table('match_tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_version_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_match_tasks_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_match_tasks_resume_version_id_resume_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_match_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_tasks'))
    )
    op.create_index(op.f('ix_match_tasks_job_id'), 'match_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_tasks_status'), 'match_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_match_tasks_user_id'), 'match_tasks', ['user_id'], unique=False)
    op.create_table('discovered_job_candidates',
    sa.Column('discovery_task_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.Column('initial_reason', sa.Text(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_task_id'], ['job_discovery_tasks.id'], name=op.f('fk_discovered_job_candidates_discovery_task_id_job_discovery_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_discovered_job_candidates_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['job_source_configs.id'], name=op.f('fk_discovered_job_candidates_source_id_job_source_configs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_job_candidates'))
    )
    op.create_index(op.f('ix_discovered_job_candidates_discovery_task_id'), 'discovered_job_candidates', ['discovery_task_id'], unique=False)
    op.create_index(op.f('ix_discovered_job_candidates_job_id'), 'discovered_job_candidates', ['job_id'], unique=False)
    op.create_table('match_reports',
    sa.Column('match_task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('resume_version_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('match_level', sa.String(length=16), nullable=False),
    sa.Column('dimension_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scoring_version', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_match_reports_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_task_id'], ['match_tasks.id'], name=op.f('fk_match_reports_match_task_id_match_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_match_reports_resume_version_id_resume_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_match_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_reports'))
    )
    op.create_index(op.f('ix_match_reports_job_id'), 'match_reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_reports_match_task_id'), 'match_reports', ['match_task_id'], unique=False)
    op.create_index(op.f('ix_match_reports_user_id'), 'match_reports', ['user_id'], unique=False)
    op.create_table('recommendation_lists',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_task_id', sa.Uuid(), nullable=True),
    sa.Column('resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_task_id'], ['job_discovery_tasks.id'], name=op.f('fk_recommendation_lists_discovery_task_id_job_discovery_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_recommendation_lists_resume_version_id_resume_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_lists'))
    )
    op.create_index(op.f('ix_recommendation_lists_discovery_task_id'), 'recommendation_lists', ['discovery_task_id'], unique=False)
    op.create_index(op.f('ix_recommendation_lists_user_id'), 'recommendation_lists', ['user_id'], unique=False)
    op.create_table('application_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_application_records_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['match_reports.id'], name=op.f('fk_application_records_report_id_match_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_application_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_records'))
    )
    op.create_index(op.f('ix_application_records_status'), 'application_records', ['status'], unique=False)
    op.create_index(op.f('ix_application_records_user_id'), 'application_records', ['user_id'], unique=False)
    op.create_table('optimization_suggestions',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rewritable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['match_reports.id'], name=op.f('fk_optimization_suggestions_report_id_match_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_suggestions'))
    )
    op.create_index(op.f('ix_optimization_suggestions_report_id'), 'optimization_suggestions', ['report_id'], unique=False)
    op.create_index(op.f('ix_optimization_suggestions_status'), 'optimization_suggestions', ['status'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('recommendation_list_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('success_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('opportunity_value', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('tier_reason', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_recommendation_items_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_list_id'], ['recommendation_lists.id'], name=op.f('fk_recommendation_items_recommendation_list_id_recommendation_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['match_reports.id'], name=op.f('fk_recommendation_items_report_id_match_reports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items'))
    )
    op.create_index(op.f('ix_recommendation_items_recommendation_list_id'), 'recommendation_items', ['recommendation_list_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_tier'), 'recommendation_items', ['tier'], unique=False)
    op.create_table('resume_rewrite_tasks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_version_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('suggestion_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_segments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rewritten_segments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('diff_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('new_resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['match_reports.id'], name=op.f('fk_resume_rewrite_tasks_report_id_match_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_resume_rewrite_tasks_resume_version_id_resume_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_rewrite_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_rewrite_tasks'))
    )
    op.create_index(op.f('ix_resume_rewrite_tasks_resume_version_id'), 'resume_rewrite_tasks', ['resume_version_id'], unique=False)
    op.create_index(op.f('ix_resume_rewrite_tasks_status'), 'resume_rewrite_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_resume_rewrite_tasks_user_id'), 'resume_rewrite_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_rewrite_tasks_user_id'), table_name='resume_rewrite_tasks')
    op.drop_index(op.f('ix_resume_rewrite_tasks_status'), table_name='resume_rewrite_tasks')
    op.drop_index(op.f('ix_resume_rewrite_tasks_resume_version_id'), table_name='resume_rewrite_tasks')
    op.drop_table('resume_rewrite_tasks')
    op.drop_index(op.f('ix_recommendation_items_tier'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_recommendation_list_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_optimization_suggestions_status'), table_name='optimization_suggestions')
    op.drop_index(op.f('ix_optimization_suggestions_report_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    op.drop_index(op.f('ix_application_records_user_id'), table_name='application_records')
    op.drop_index(op.f('ix_application_records_status'), table_name='application_records')
    op.drop_table('application_records')
    op.drop_index(op.f('ix_recommendation_lists_user_id'), table_name='recommendation_lists')
    op.drop_index(op.f('ix_recommendation_lists_discovery_task_id'), table_name='recommendation_lists')
    op.drop_table('recommendation_lists')
    op.drop_index(op.f('ix_match_reports_user_id'), table_name='match_reports')
    op.drop_index(op.f('ix_match_reports_match_task_id'), table_name='match_reports')
    op.drop_index(op.f('ix_match_reports_job_id'), table_name='match_reports')
    op.drop_table('match_reports')
    op.drop_index(op.f('ix_discovered_job_candidates_job_id'), table_name='discovered_job_candidates')
    op.drop_index(op.f('ix_discovered_job_candidates_discovery_task_id'), table_name='discovered_job_candidates')
    op.drop_table('discovered_job_candidates')
    op.drop_index(op.f('ix_match_tasks_user_id'), table_name='match_tasks')
    op.drop_index(op.f('ix_match_tasks_status'), table_name='match_tasks')
    op.drop_index(op.f('ix_match_tasks_job_id'), table_name='match_tasks')
    op.drop_table('match_tasks')
    op.drop_index(op.f('ix_job_discovery_tasks_user_id'), table_name='job_discovery_tasks')
    op.drop_index(op.f('ix_job_discovery_tasks_status'), table_name='job_discovery_tasks')
    op.drop_table('job_discovery_tasks')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_job_analyses_job_id'), table_name='job_analyses')
    op.drop_table('job_analyses')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_model_call_logs_user_id'), table_name='model_call_logs')
    op.drop_index(op.f('ix_model_call_logs_task_type'), table_name='model_call_logs')
    op.drop_table('model_call_logs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_source_configs_user_id'), table_name='job_source_configs')
    op.drop_table('job_source_configs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_scoring_rules_name'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
