/**
 * Parity tests: the in-browser TypeScript AI port must produce the *same*
 * results as the Python backend (`services/api/app/ai/*`). The expected values
 * below were generated by running the backend modules directly.
 */
import { describe, expect, it } from "vitest";

import { deterministicEmbedding, tokenize } from "@/lib/ai/embedding";
import { parseJd, parseResume } from "@/lib/ai/extraction";
import { scoreMatch, type ScoreInputs } from "@/lib/ai/scoring/engine";
import { generateSuggestions } from "@/lib/ai/scoring/suggestions";

const RESUME_TEXT =
  "教育背景\n北京大学 应用统计学 硕士\n实习经历\n" +
  "负责数据分析，使用 SQL 与 Python 完成用户增长分析，留存提升 8%\n" +
  "项目经历\n搭建 A/B 测试看板，覆盖 500 万 UV";
const JD_TEXT =
  "岗位职责\n负责用户增长数据分析，搭建增长模型\n任职要求\n" +
  "熟练 SQL、Python、Hive；有 Tableau 经验优先";

describe("AI port parity with the Python backend", () => {
  it("tokenizes mixed CN/EN text identically", () => {
    expect(tokenize("数据分析 Python A/B test")).toEqual([
      "python",
      "a",
      "b",
      "test",
      "数",
      "据",
      "分",
      "析",
      "数据",
      "据分",
      "分析",
    ]);
  });

  it("produces a deterministic, L2-normalised embedding", () => {
    const emb = deterministicEmbedding("数据分析 Python SQL 用户增长");
    expect(emb).toHaveLength(256);
    expect(emb.filter((v) => v !== 0)).toHaveLength(16);
    const norm = Math.sqrt(emb.reduce((acc, v) => acc + v * v, 0));
    expect(norm).toBeCloseTo(1, 10);
  });

  it("extracts the same resume skill tags and JD analysis", () => {
    const pr = parseResume(RESUME_TEXT);
    expect(pr.skillTags).toEqual(["A/B 实验", "Python", "SQL", "数据分析", "统计分析"]);

    const pj = parseJd(JD_TEXT);
    expect(pj.hardSkills).toEqual(["Python", "SQL", "Tableau", "数据分析"]);
    expect(pj.keywords.slice(0, 5)).toEqual([
      { term: "增长", weight: 1.0 },
      { term: "hive", weight: 0.96 },
      { term: "python", weight: 0.92 },
      { term: "sql", weight: 0.88 },
      { term: "tableau", weight: 0.84 },
    ]);
  });

  it("scores a match identically to MatchScorer", () => {
    const pr = parseResume(RESUME_TEXT);
    const pj = parseJd(JD_TEXT);
    const inputs: ScoreInputs = {
      resumeSkillTags: pr.skillTags,
      resumeText: RESUME_TEXT,
      resumeEmbedding: deterministicEmbedding(pr.skillTags.join(" ")),
      jobHardSkills: pj.hardSkills,
      jobSoftSkills: pj.softSkills,
      jobRequirements: pj.requirements,
      jobResponsibilities: pj.responsibilities,
      jobKeywords: pj.keywords,
      jobEmbedding: deterministicEmbedding(JD_TEXT),
      jobCity: "上海",
      targetCities: ["上海", "杭州"],
    };
    const res = scoreMatch(inputs);

    expect(res.overallScore).toBe(64);
    expect(res.matchLevel).toBe("medium");
    expect(res.matchedHardSkills).toEqual(["Python", "SQL", "数据分析"]);
    expect(res.missingHardSkills).toEqual(["Tableau"]);
    expect(res.dimensionScores.map((d) => [d.code, d.score, d.weight])).toEqual([
      ["hard_skills", 75, 25],
      ["experience", 57, 25],
      ["keywords", 43, 15],
      ["basic_conditions", 93, 10],
      ["soft_skills_interest", 70, 10],
      ["expression_quality", 90, 10],
    ]);
    expect(generateSuggestions(res)).toHaveLength(2);
  });
});
